/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sebastián
 */
public class MenuAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form Menú
     */
    public MenuAdministrador() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAtras = new javax.swing.JButton();
        btnRegisProvee = new javax.swing.JButton();
        btnRegisPedidos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRegisCategoria = new javax.swing.JButton();
        btnRegisProduc1 = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(247, 199, 27));
        setFocusable(false);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(237, 148, 1));

        btnAtras.setBackground(new java.awt.Color(204, 204, 0));
        btnAtras.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/flecha-hacia-atras (1).png"))); // NOI18N
        btnAtras.setText("Salir");
        btnAtras.setToolTipText("");
        btnAtras.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnAtras.setContentAreaFilled(false);
        btnAtras.setFocusPainted(false);
        btnAtras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/flecha-hacia-atras _grande.png"))); // NOI18N
        btnAtras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnRegisProvee.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRegisProvee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/logo-ferrebuentrato.png"))); // NOI18N
        btnRegisProvee.setText("REGISTRAR PROVEEDORES");
        btnRegisProvee.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnRegisProvee.setContentAreaFilled(false);
        btnRegisProvee.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegisProvee.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/cropped-logo-ferrebuentrato_grande.png"))); // NOI18N
        btnRegisProvee.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegisProvee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisProveeActionPerformed(evt);
            }
        });

        btnRegisPedidos.setBackground(new java.awt.Color(204, 51, 0));
        btnRegisPedidos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRegisPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/todolist1.png"))); // NOI18N
        btnRegisPedidos.setText("REGISTRAR PEDIDOS");
        btnRegisPedidos.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnRegisPedidos.setContentAreaFilled(false);
        btnRegisPedidos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegisPedidos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/todolist1_grande.png"))); // NOI18N
        btnRegisPedidos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegisPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisPedidosActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/ferreteria-logo-png-1.png"))); // NOI18N

        jLabel2.setText("Baratito © 2019");

        btnRegisCategoria.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRegisCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/40395-icono-de-herramientas.png"))); // NOI18N
        btnRegisCategoria.setText("REGISTRAR CATEGORIA");
        btnRegisCategoria.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnRegisCategoria.setContentAreaFilled(false);
        btnRegisCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegisCategoria.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/40395-icono-de-herramientas_grande.png"))); // NOI18N
        btnRegisCategoria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegisCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisCategoriaActionPerformed(evt);
            }
        });

        btnRegisProduc1.setBackground(new java.awt.Color(204, 204, 0));
        btnRegisProduc1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRegisProduc1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/classica_hammer-and-wrench_flat-circle-white-on-red_512x512.png"))); // NOI18N
        btnRegisProduc1.setText("REGISTRAR PRODUCTOS");
        btnRegisProduc1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnRegisProduc1.setContentAreaFilled(false);
        btnRegisProduc1.setFocusPainted(false);
        btnRegisProduc1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegisProduc1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/classica_hammer-and-wrench_flat-circle-white-on-red_grande.png"))); // NOI18N
        btnRegisProduc1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegisProduc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisProduc1ActionPerformed(evt);
            }
        });

        btnUsuarios.setBackground(new java.awt.Color(255, 225, 99));
        btnUsuarios.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUsuarios.setText("USUARIOS");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnRegisProduc1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegisPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(btnRegisCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnRegisProvee)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(110, 110, 110)
                        .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAtras)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnRegisProvee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegisPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnRegisProduc1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegisCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisProduc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisProduc1ActionPerformed
        try {
            Productos productos = new Productos();
            productos.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegisProduc1ActionPerformed

    private void btnRegisPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisPedidosActionPerformed
            
        try {
            Pedidos pedidos = new Pedidos();
            pedidos.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegisPedidosActionPerformed

    private void btnRegisCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisCategoriaActionPerformed
        try {
            Categorias categorias =new Categorias();
            categorias.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Menú.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegisCategoriaActionPerformed

    private void btnRegisProveeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisProveeActionPerformed
        try {
            Proveedores proveedores = new Proveedores();
            proveedores.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Menú.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegisProveeActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
            System.exit(0);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        try {
            RegistrarUsuario regisusuario = new RegistrarUsuario();
            regisusuario.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menú().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnRegisCategoria;
    private javax.swing.JButton btnRegisPedidos;
    private javax.swing.JButton btnRegisProduc1;
    private javax.swing.JButton btnRegisProvee;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
