package Presentacion;

import Datos.Conexion;
import Datos.PedidoDB;
import Entidad.Pedido;
import Logica.PedidoL;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

public class Pedidos extends javax.swing.JFrame {

    PedidoL objPedidosL = new PedidoL();
    Pedido objPedido = new Pedido();
    PedidoDB PEDIDO = new PedidoDB();
    DefaultTableModel modelo = new DefaultTableModel();
    Date fecha;

    public Pedidos() throws SQLException {
        initComponents();
        cargarjtabla();
        PEDIDO.Combo_box(cboRazonSocial);
        this.setLocationRelativeTo(null);

    }

    public void limpiar() {
        txtCantPedido.setText("");
        txtCodPed.setText("");
        cboRazonSocial.setSelectedItem(-1);
        txtDescripPedido.setText("");
        txtFechaEntrega.setText("");
        txtPrecTotalPedido.setText("");
        txtPrecioUniPedido.setText("");
        txtRucProveePed.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodPed = new javax.swing.JTextField();
        txtRucProveePed = new javax.swing.JTextField();
        txtDescripPedido = new javax.swing.JTextField();
        txtCantPedido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPrecioUniPedido = new javax.swing.JTextField();
        txtPrecTotalPedido = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnBuscarPed = new javax.swing.JButton();
        btnAñadirPed = new javax.swing.JButton();
        btnActuPed = new javax.swing.JButton();
        btnElimPed = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtablaPedidos = new javax.swing.JScrollPane();
        jtablepedidos = new javax.swing.JTable();
        txtFechaEntrega = new javax.swing.JFormattedTextField();
        cboRazonSocial = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        btnbuscapro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(61, 98, 184));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Codigo de pedido:");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ruc Proveedor:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descripción del producto:");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad del Pedido:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha de entrega:");

        txtCodPed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodPedKeyTyped(evt);
            }
        });

        txtRucProveePed.setEditable(false);
        txtRucProveePed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRucProveePedKeyTyped(evt);
            }
        });

        txtDescripPedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripPedidoKeyTyped(evt);
            }
        });

        txtCantPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantPedidoActionPerformed(evt);
            }
        });
        txtCantPedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantPedidoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantPedidoKeyTyped(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Precio por unidad:");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Precio Total:");

        txtPrecioUniPedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioUniPedidoKeyTyped(evt);
            }
        });

        txtPrecTotalPedido.setEnabled(false);
        txtPrecTotalPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecTotalPedidoActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Razón Social:");

        btnBuscarPed.setBackground(new java.awt.Color(153, 255, 153));
        btnBuscarPed.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBuscarPed.setText("Buscar");
        btnBuscarPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPedActionPerformed(evt);
            }
        });

        btnAñadirPed.setBackground(new java.awt.Color(255, 255, 153));
        btnAñadirPed.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAñadirPed.setText("Añadir");
        btnAñadirPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirPedActionPerformed(evt);
            }
        });

        btnActuPed.setBackground(new java.awt.Color(153, 153, 255));
        btnActuPed.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnActuPed.setText("Actualizar");
        btnActuPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActuPedActionPerformed(evt);
            }
        });

        btnElimPed.setBackground(new java.awt.Color(255, 153, 153));
        btnElimPed.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnElimPed.setText("Eliminar");
        btnElimPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimPedActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 14, 36));
        jPanel1.setForeground(new java.awt.Color(0, 15, 47));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Atras_png (2).png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 0));
        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("REGISTRO Y SUPRESIÓN DE PEDIDOS");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/ferreteria-logo-png_icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jtablaPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablaPedidosMouseClicked(evt);
            }
        });

        jtablepedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtablepedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablepedidosMouseClicked(evt);
            }
        });
        jtablaPedidos.setViewportView(jtablepedidos);

        try {
            txtFechaEntrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel12.setText("Búsqueda:");

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });

        btnbuscapro.setText("B...");
        btnbuscapro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscaproActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAñadirPed, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarPed, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActuPed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnElimPed, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel2))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(txtRucProveePed, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnbuscapro))
                                        .addComponent(cboRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtCodPed, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(90, 90, 90))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDescripPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrecioUniPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCantPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrecTotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtablaPedidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodPed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(8, 8, 8)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRucProveePed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(btnbuscapro)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cboRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDescripPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtPrecioUniPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCantPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtPrecTotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jtablaPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAñadirPed, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPed, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActuPed, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnElimPed, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        Menú menú = new Menú();
        menú.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void btnAñadirPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirPedActionPerformed
        if (txtCodPed.getText().isEmpty()||txtDescripPedido.getText().isEmpty()||txtFechaEntrega.getText().isEmpty()||txtCantPedido.getText().isEmpty()||txtPrecioUniPedido.getText().isEmpty()||txtPrecTotalPedido.getText().isEmpty()||txtRucProveePed.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,"Campos vacios, verifique su información");
        }
        else{
        modelo.addRow(new Object[]{txtCodPed.getText(), cboRazonSocial.getSelectedItem(), txtRucProveePed.getText(), txtDescripPedido.getText(), txtFechaEntrega.getText(), txtPrecioUniPedido.getText(), txtCantPedido.getText(), txtPrecTotalPedido.getText()});
        jtablepedidos.setModel(modelo);
        try {
            cargarjtabla();
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        objPedido.setCodigo_Pedido(txtCodPed.getText());
        objPedido.setRuc_Provee((txtRucProveePed.getText()));
        objPedido.setRazon_Social((String) cboRazonSocial.getSelectedItem());
        objPedido.setDescrip_Pedido(txtDescripPedido.getText());
        objPedido.setFecha_Entrega(txtFechaEntrega.getText());
        objPedido.setPrecio_Uni(Double.parseDouble(txtPrecioUniPedido.getText()));
        objPedido.setCant_Pedido(Double.parseDouble(txtCantPedido.getText()));
        objPedido.setPrecio_Total(Double.parseDouble(txtPrecTotalPedido.getText()));

        if (objPedidosL.Graba_Pedido(objPedido)) {
            JOptionPane.showMessageDialog(null, "Se grabó correctamente");
            try {
                cargarjtabla();
            } catch (SQLException ex) {
                Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
            }
            limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "No se grabó correctamente");
        }
        }
    }//GEN-LAST:event_btnAñadirPedActionPerformed

    private void txtCodPedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodPedKeyTyped
        if (txtCodPed.getText().length() >= 4) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtCodPedKeyTyped

    private void txtRucProveePedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRucProveePedKeyTyped
        if (txtRucProveePed.getText().length() >= 11) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtRucProveePedKeyTyped

    private void txtPrecTotalPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecTotalPedidoActionPerformed

    }//GEN-LAST:event_txtPrecTotalPedidoActionPerformed

    private void txtCantPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantPedidoActionPerformed

        try {
            double precio;
            int cantidad;
            int total;
            precio = Double.parseDouble(txtPrecioUniPedido.getText());
            cantidad = Integer.parseInt(txtCantPedido.getText());
            total = (int) (precio * cantidad);
            txtPrecTotalPedido.setText(String.valueOf(total));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error");
        }

    }//GEN-LAST:event_txtCantPedidoActionPerformed

    private void jtablepedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablepedidosMouseClicked

        DefaultTableModel model = (DefaultTableModel) jtablepedidos.getModel();
        int SelectedRowIndex = jtablepedidos.getSelectedRow();
        txtCodPed.setText(model.getValueAt(SelectedRowIndex, 0).toString());
        cboRazonSocial.setSelectedItem(model.getValueAt(SelectedRowIndex, 1).toString());
        txtRucProveePed.setText(model.getValueAt(SelectedRowIndex, 2).toString());
        txtDescripPedido.setText(model.getValueAt(SelectedRowIndex, 3).toString());
        txtFechaEntrega.setText(model.getValueAt(SelectedRowIndex, 4).toString());
        txtPrecioUniPedido.setText(model.getValueAt(SelectedRowIndex, 5).toString());
        txtCantPedido.setText(model.getValueAt(SelectedRowIndex, 6).toString());
        txtPrecTotalPedido.setText(model.getValueAt(SelectedRowIndex, 7).toString());
    }//GEN-LAST:event_jtablepedidosMouseClicked

    private void btnActuPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActuPedActionPerformed
        objPedido.setCodigo_Pedido(txtCodPed.getText());
        objPedido.setRazon_Social(String.valueOf(cboRazonSocial.getSelectedItem()));
        objPedido.setRuc_Provee(txtRucProveePed.getText());
        objPedido.setDescrip_Pedido(txtDescripPedido.getText());
        objPedido.setFecha_Entrega(txtFechaEntrega.getText());
        objPedido.setPrecio_Uni(Double.parseDouble((txtPrecioUniPedido.getText())));
        objPedido.setCant_Pedido(Double.parseDouble((txtCantPedido.getText())));
        objPedido.setPrecio_Total(Double.parseDouble((txtPrecTotalPedido.getText())));

        if (objPedidosL.Actualiza_Pedido(objPedido)) {
            JOptionPane.showMessageDialog(null, "Se modificó correctamente");
            try {
                cargarjtabla();
            } catch (SQLException ex) {
                Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
            }
            limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "No se modificó correctamente");
        }
    }//GEN-LAST:event_btnActuPedActionPerformed

    private void btnBuscarPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPedActionPerformed
        objPedido = objPedidosL.Busca_Pedido(JOptionPane.showInputDialog("Inserte su Codigo de Pedido"));
        if ((objPedido.getDescrip_Pedido() == "Nada")) {
            JOptionPane.showMessageDialog(null, "Codigo no existe");
            limpiar();
        } else {
            limpiar();
            txtCodPed.setText(objPedido.getCodigo_Pedido());
            cboRazonSocial.setSelectedItem(objPedido.getRazon_Social());
            txtRucProveePed.setText(objPedido.getRuc_Provee());
            txtDescripPedido.setText(objPedido.getDescrip_Pedido());
            txtFechaEntrega.setText(objPedido.getFecha_Entrega());
            txtPrecioUniPedido.setText(String.valueOf(objPedido.getPrecio_Uni()));
            txtCantPedido.setText(String.valueOf(objPedido.getCant_Pedido()));
            txtPrecTotalPedido.setText(String.valueOf(objPedido.getPrecio_Total()));

        }
    }//GEN-LAST:event_btnBuscarPedActionPerformed

    private void txtDescripPedidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripPedidoKeyTyped

    }//GEN-LAST:event_txtDescripPedidoKeyTyped

    private void txtCantPedidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantPedidoKeyReleased
        double preciot;
        double preciou = Double.parseDouble(txtPrecioUniPedido.getText());
        int cant = Integer.parseInt(txtCantPedido.getText());

        preciot = preciou * cant;

        txtPrecTotalPedido.setText(String.valueOf(preciot));
    }//GEN-LAST:event_txtCantPedidoKeyReleased
    public void cargarjtabla() throws SQLException {
        jtablepedidos.setModel(DbUtils.resultSetToTableModel(objPedidosL.fillDetalle()));
    }
    private void jtablaPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaPedidosMouseClicked

    }//GEN-LAST:event_jtablaPedidosMouseClicked

    private void btnElimPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimPedActionPerformed
        if (objPedidosL.Eliminar_Producto((txtCodPed.getText()))) {
            JOptionPane.showMessageDialog(null, "Se eliminó con éxito");
            try {
                cargarjtabla();
            } catch (SQLException ex) {
                Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
            }
            limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "No se eliminó");
        }
    }//GEN-LAST:event_btnElimPedActionPerformed

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        String pedido = txtBusqueda.getText();
        buscarporcod(pedido);
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void btnbuscaproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscaproActionPerformed
        try {
            ProveedoresE P=new ProveedoresE();
            P.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnbuscaproActionPerformed

    private void txtPrecioUniPedidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioUniPedidoKeyTyped
     char a = evt.getKeyChar();
     
        if (!Character.isDigit(a) && (a <'.'|| a>'.')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioUniPedidoKeyTyped

    private void txtCantPedidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantPedidoKeyTyped
      char a = evt.getKeyChar();
     
        if (!Character.isDigit(a) && (a <'.'|| a>'.')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCantPedidoKeyTyped
    public void buscarporcod(String text) {
        DefaultTableModel result = objPedidosL.BarraBuscarPedido(text);
        jtablepedidos.setModel(result);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Pedidos().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActuPed;
    private javax.swing.JButton btnAñadirPed;
    private javax.swing.JButton btnBuscarPed;
    private javax.swing.JButton btnElimPed;
    private javax.swing.JButton btnbuscapro;
    public static javax.swing.JComboBox<String> cboRazonSocial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jtablaPedidos;
    private javax.swing.JTable jtablepedidos;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCantPedido;
    private javax.swing.JTextField txtCodPed;
    private javax.swing.JTextField txtDescripPedido;
    private javax.swing.JFormattedTextField txtFechaEntrega;
    private javax.swing.JTextField txtPrecTotalPedido;
    private javax.swing.JTextField txtPrecioUniPedido;
    public static javax.swing.JTextField txtRucProveePed;
    // End of variables declaration//GEN-END:variables
}
