package Presentacion;

import Datos.Conexion;
import Datos.ProductoDB;
import Entidad.Producto;
import Logica.ProductosL;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
//import java.time.LocalDate;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

public class Productos extends javax.swing.JFrame {

    ProductosL objProductoL = new ProductosL();
    Producto objProducto = new Producto();
    ProductoDB PRODUCTO = new ProductoDB();
    DefaultTableModel modelo = new DefaultTableModel();
//    Date fechasql;
//    Date fechautil;

    public Productos() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        PRODUCTO.Combo_box(cboCategoria);
        modelo.addColumn("Cod.Prod");
        modelo.addColumn("Categoria");
        modelo.addColumn("Cod.Cat");
        modelo.addColumn("Descrip");
        modelo.addColumn("Marca");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Valor.U");
        modelo.addColumn("Unidad.M");
        modelo.addColumn("Fecha.Reg");
        jtablaProductos.setModel(modelo);
        cargarjtabla();
        cboUniMedida.removeAllItems();
        cboUniMedida.addItem("Seleccione unidad");
        cboUniMedida.addItem("Kilos");
        cboUniMedida.addItem("Unidad");
        cboUniMedida.addItem("Cientos");
        cboUniMedida.addItem("Galon");
        cboUniMedida.addItem("Rollo");
        cboUniMedida.addItem("Pliego");

    }

    public void cargarjtabla() throws SQLException {
        jtablaProductos.setModel(DbUtils.resultSetToTableModel(objProductoL.fillProducto()));
    }

    public void buscarporcod(String text) {
        DefaultTableModel result = objProductoL.BarraBuscarProducto(text);
        jtablaProductos.setModel(result);
    }

    public void limpiar() {
        txtCodProd.setText("");
        txtCodCat.setText("");
        txtCantProd.setText("");
        txtDescripProd.setText("");
        txtFechaRegistro.setText("");
        txtMarcaProd.setText("");
        txtVUProd.setText("");
        cboUniMedida.setSelectedIndex(-1);
        cboCategoria.setSelectedIndex(-1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtCodProd = new javax.swing.JTextField();
        txtDescripProd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtMarcaProd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCantProd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtVUProd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cboUniMedida = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCodCat = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnElimProd = new javax.swing.JButton();
        btnActuProd = new javax.swing.JButton();
        btnBuscarProd = new javax.swing.JButton();
        btnAñadirProd = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cboCategoria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtablaProductos = new javax.swing.JTable();
        txtFechaRegistro = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        btnbuscarcat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(73, 126, 118));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha de registro:");

        txtCodProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodProdKeyTyped(evt);
            }
        });

        txtDescripProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripProdKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Código de producto:");

        txtMarcaProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMarcaProdKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descripción:");

        txtCantProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantProdKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Marca:");

        txtVUProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVUProdKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad:");

        cboUniMedida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cboUniMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboUniMedidaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Valor Unitario:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Unidad de medida:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Código de Categoria:");

        txtCodCat.setEditable(false);
        txtCodCat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodCatKeyTyped(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("REGISTRO Y SUPRESIÓN DE PRODUCTOS");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Atras_png (2).png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/ferreteria-logo-png_icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnElimProd.setBackground(new java.awt.Color(255, 153, 153));
        btnElimProd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnElimProd.setText("Eliminar");
        btnElimProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimProdActionPerformed(evt);
            }
        });

        btnActuProd.setBackground(new java.awt.Color(255, 255, 153));
        btnActuProd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnActuProd.setText("Actualizar");
        btnActuProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActuProdActionPerformed(evt);
            }
        });

        btnBuscarProd.setBackground(new java.awt.Color(204, 153, 255));
        btnBuscarProd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBuscarProd.setText("Buscar");
        btnBuscarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdActionPerformed(evt);
            }
        });

        btnAñadirProd.setBackground(new java.awt.Color(102, 255, 102));
        btnAñadirProd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAñadirProd.setText("Añadir");
        btnAñadirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirProdActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Categoria:");

        jtablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtablaProductos);

        try {
            txtFechaRegistro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel13.setText("Búsqueda:");

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });

        btnbuscarcat.setText("B...");
        btnbuscarcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarcatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAñadirProd)
                        .addGap(9, 9, 9)
                        .addComponent(btnBuscarProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActuProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnElimProd))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12))
                            .addGap(9, 9, 9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtCodCat, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnbuscarcat))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(27, 27, 27)
                            .addComponent(cboUniMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel7)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5))
                            .addGap(30, 30, 30)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtVUProd, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDescripProd, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMarcaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCantProd, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFechaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(btnbuscarcat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtDescripProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMarcaProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cboUniMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCantProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtVUProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtFechaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAñadirProd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActuProd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnElimProd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscarcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarcatActionPerformed
        try {
            CategoriaE C =new CategoriaE();
            C.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnbuscarcatActionPerformed

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        String producto = txtBusqueda.getText();
        buscarporcod(producto);
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void jtablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaProductosMouseClicked
        DefaultTableModel model = (DefaultTableModel) jtablaProductos.getModel();
        int SelectedRowIndex = jtablaProductos.getSelectedRow();
        txtCodProd.setText(model.getValueAt(SelectedRowIndex, 0).toString());
        cboCategoria.setSelectedItem(model.getValueAt(SelectedRowIndex, 1).toString());
        txtCodCat.setText(model.getValueAt(SelectedRowIndex, 2).toString());
        txtDescripProd.setText(model.getValueAt(SelectedRowIndex, 3).toString());
        txtMarcaProd.setText(model.getValueAt(SelectedRowIndex, 4).toString());
        txtCantProd.setText(model.getValueAt(SelectedRowIndex, 5).toString());
        txtVUProd.setText(model.getValueAt(SelectedRowIndex, 6).toString());
        cboUniMedida.setSelectedItem(model.getValueAt(SelectedRowIndex, 7).toString());
        txtFechaRegistro.setText(model.getValueAt(SelectedRowIndex, 8).toString());
    }//GEN-LAST:event_jtablaProductosMouseClicked

    private void btnAñadirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirProdActionPerformed
        if (txtCodProd.getText().isEmpty() || txtCodCat.getText().isEmpty() || txtDescripProd.getText().isEmpty()|| txtMarcaProd.getText().isEmpty() || txtVUProd.getText().isEmpty() || txtFechaRegistro.getText().isEmpty() || txtCantProd.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Campos vacios, verifique su información");
        }
        else {
            modelo.addRow(new Object[]{txtCodProd.getText(),cboCategoria.getSelectedItem(),txtCodCat.getText(),txtDescripProd.getText(),txtMarcaProd.getText(),txtCantProd.getText(),txtVUProd.getText(),cboUniMedida.getSelectedItem(),txtFechaRegistro.getText()});
            jtablaProductos.setModel(modelo);
            objProducto.setCod_Producto(txtCodProd.getText());
            objProducto.setCod_Categoria(txtCodCat.getText());
            objProducto.setCate_Prod((String) cboCategoria.getSelectedItem());
            objProducto.setDescrip_Producto(txtDescripProd.getText());
            objProducto.setMarca(txtMarcaProd.getText());
            objProducto.setCantidad(Double.parseDouble(txtCantProd.getText()));
            objProducto.setValor_Unitario(Double.parseDouble(txtVUProd.getText()));
            objProducto.setUnidad_Medida((String) cboUniMedida.getSelectedItem());
            objProducto.setFecha_Registro(txtFechaRegistro.getText());
            //        fechasql = txtFechaProd.getDate();
            //        long ab = fechasql.getTime();
            //        java.sql.Date fecha1 = new java.sql.Date(ab);
            //        objProducto.setFecha_Registro(fecha1);

            //        JOptionPane.showMessageDialog(null, fecha1);
            if (objProductoL.Graba_Producto(objProducto)) {
                JOptionPane.showMessageDialog(null, "Se grabó correctamente");
                try {
                    cargarjtabla();
                } catch (SQLException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                }
                limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "No se grabó correctamente");
            }
        }
    }//GEN-LAST:event_btnAñadirProdActionPerformed

    private void btnBuscarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdActionPerformed

        objProducto = objProductoL.Busca_Producto(JOptionPane.showInputDialog("Inserte su Codigo de Producto"));
        if ((objProducto.getDescrip_Producto() == "Nada")) {
            JOptionPane.showMessageDialog(null, "Codigo no existe");
            limpiar();
        } else {
            limpiar();
            txtCodCat.setText(objProducto.getCod_Categoria());
            txtCodProd.setText(objProducto.getCod_Producto());
            txtDescripProd.setText(objProducto.getDescrip_Producto());
            txtCantProd.setText(String.valueOf((objProducto.getCantidad())));
            txtFechaRegistro.setText(objProducto.getCate_Prod());
            //            fechautil = objProducto.getFecha_Registro();
            //            long abc = fechautil.getTime();
            //            java.sql.Date fecha2 = new java.sql.Date(abc);
            //            txtFechaProd.setDate(fecha2);
            txtMarcaProd.setText(objProducto.getMarca());
            txtVUProd.setText(String.valueOf(objProducto.getValor_Unitario()));
            cboUniMedida.setSelectedItem(objProducto.getUnidad_Medida());
        }
    }//GEN-LAST:event_btnBuscarProdActionPerformed

    private void btnActuProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActuProdActionPerformed

        objProducto.setCod_Categoria(txtCodCat.getText());
        objProducto.setCod_Producto(txtCodProd.getText());
        objProducto.setCate_Prod(String.valueOf((cboCategoria.getSelectedItem())));
        objProducto.setDescrip_Producto(txtDescripProd.getText());
        objProducto.setCantidad(Double.valueOf((txtCantProd.getText())));
        objProducto.setFecha_Registro(txtFechaRegistro.getText());
        objProducto.setMarca(txtMarcaProd.getText());
        objProducto.setValor_Unitario(Double.valueOf(txtVUProd.getText()));
        objProducto.setUnidad_Medida(String.valueOf((cboUniMedida.getSelectedItem())));

        if (objProductoL.Actualiza_Producto(objProducto)) {
            JOptionPane.showMessageDialog(null, "Se modificó correctamente");
            try {
                cargarjtabla();
            } catch (SQLException ex) {
                Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            }
            limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "No se modificó correctamente");
        }
    }//GEN-LAST:event_btnActuProdActionPerformed

    private void btnElimProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimProdActionPerformed
        if (objProductoL.Eliminar_Producto((txtCodProd.getText()))) {
            JOptionPane.showMessageDialog(null, "Se eliminó con éxito");
            try {
                cargarjtabla();
            } catch (SQLException ex) {
                Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            }
            limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "No se eliminó");
        }
    }//GEN-LAST:event_btnElimProdActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        Menú menú = new Menú();
        menú.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void txtCodCatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodCatKeyTyped
        char a = evt.getKeyChar();
        if (!Character.isDigit(a)) {
            evt.consume();
        }
        //LIMITE DE CARACTERES//
        if (txtCodCat.getText().length() >= 4) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtCodCatKeyTyped

    private void txtVUProdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVUProdKeyTyped
      char a = evt.getKeyChar();
     
        if (!Character.isDigit(a) && (a <'.'|| a>'.')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtVUProdKeyTyped

    private void txtCantProdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantProdKeyTyped
        char a = evt.getKeyChar();
        if (!Character.isDigit(a)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCantProdKeyTyped

    private void txtMarcaProdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMarcaProdKeyTyped
          Character a = evt.getKeyChar();
        if (!Character.isLetter(a) && a !=KeyEvent.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMarcaProdKeyTyped

    private void txtDescripProdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripProdKeyTyped

    }//GEN-LAST:event_txtDescripProdKeyTyped

    private void txtCodProdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodProdKeyTyped
        char a = evt.getKeyChar();
        if (!Character.isDigit(a)) {
            evt.consume();
        }
        //LIMITE DE CARACTERES//
        if (txtCodProd.getText().length() >= 6) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtCodProdKeyTyped

    private void cboUniMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboUniMedidaActionPerformed
        
    }//GEN-LAST:event_cboUniMedidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Productos().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActuProd;
    private javax.swing.JButton btnAñadirProd;
    private javax.swing.JButton btnBuscarProd;
    private javax.swing.JButton btnElimProd;
    private javax.swing.JButton btnbuscarcat;
    public static javax.swing.JComboBox<String> cboCategoria;
    private javax.swing.JComboBox<String> cboUniMedida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtablaProductos;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCantProd;
    public static javax.swing.JTextField txtCodCat;
    private javax.swing.JTextField txtCodProd;
    private javax.swing.JTextField txtDescripProd;
    private javax.swing.JFormattedTextField txtFechaRegistro;
    private javax.swing.JTextField txtMarcaProd;
    private javax.swing.JTextField txtVUProd;
    // End of variables declaration//GEN-END:variables

}
