/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.Conexion;
import Datos.ProveedorDB;
import Entidad.Proveedor;
import Logica.ProveedoresL;
import java.awt.event.KeyEvent;
import java.util.List;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Sebastián
 */
public class Proveedores extends javax.swing.JFrame {

    ProveedoresL objProveedoresL = new ProveedoresL();
    Proveedor objProveedor = new Proveedor();
    DefaultTableModel modelo = new DefaultTableModel();

    public Proveedores() throws SQLException {

        initComponents();

        modelo.addColumn("Ruc");
        modelo.addColumn("Telefono");
        modelo.addColumn("Nombre/Razon social");
        modelo.addColumn("Direccion");
        modelo.addColumn("Correo");
        jtablaProveedor.setModel(modelo);
        cargarjtabla();

        this.setLocationRelativeTo(null);

    }

    public void limpiar() {
        txtNomProvee.setText("");
        txtRucProvee.setText("");
        txtTeleProvee.setText("");
        txtCorreo.setText("");
        txtDireccion.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRucProvee = new javax.swing.JTextField();
        txtNomProvee = new javax.swing.JTextField();
        txtTeleProvee = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnAñadirProvee = new javax.swing.JButton();
        btnElimiProvee = new javax.swing.JButton();
        btnActuProvee = new javax.swing.JButton();
        btnBuscarProvee = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtablaa = new javax.swing.JScrollPane();
        jtablaProveedor = new javax.swing.JTable();
        txtBusqueda = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(14, 96, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Telefono:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre/Razón Social:");

        txtRucProvee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRucProveeKeyTyped(evt);
            }
        });

        txtNomProvee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomProveeKeyTyped(evt);
            }
        });

        txtTeleProvee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTeleProveeKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dirección:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Correo:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ruc:");

        btnAñadirProvee.setBackground(new java.awt.Color(102, 255, 255));
        btnAñadirProvee.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAñadirProvee.setText("Agregar");
        btnAñadirProvee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirProveeActionPerformed(evt);
            }
        });

        btnElimiProvee.setBackground(new java.awt.Color(255, 153, 153));
        btnElimiProvee.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnElimiProvee.setText("Eliminar");
        btnElimiProvee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimiProveeActionPerformed(evt);
            }
        });

        btnActuProvee.setBackground(new java.awt.Color(255, 204, 102));
        btnActuProvee.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnActuProvee.setText("Actualizar");
        btnActuProvee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActuProveeActionPerformed(evt);
            }
        });

        btnBuscarProvee.setBackground(new java.awt.Color(255, 255, 102));
        btnBuscarProvee.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBuscarProvee.setText("Buscar");
        btnBuscarProvee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProveeActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(16, 184, 24));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Atras_png (2).png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO Y SUPRESIÓN DE PROVEEDORES");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/ferreteria-logo-png_icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jtablaa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablaaMouseClicked(evt);
            }
        });

        jtablaProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtablaProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablaProveedorMouseClicked(evt);
            }
        });
        jtablaa.setViewportView(jtablaProveedor);

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });

        jLabel7.setText("Búsqueda:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAñadirProvee, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarProvee, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActuProvee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnElimiProvee, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtRucProvee, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomProvee, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTeleProvee, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtablaa, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRucProvee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTeleProvee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNomProvee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAñadirProvee, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarProvee, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActuProvee, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnElimiProvee, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtablaa, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRucProveeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRucProveeKeyTyped
        char a = evt.getKeyChar();
        if (!Character.isDigit(a)) {
            evt.consume();
        }
        //LIMITE DE CARACTERES//
        if (txtRucProvee.getText().length() == 11/*LIMITE*/) {
            evt.consume();
        }
    }//GEN-LAST:event_txtRucProveeKeyTyped

    private void txtNomProveeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomProveeKeyTyped
        Character a = evt.getKeyChar();
        if (!Character.isLetter(a) && a !=KeyEvent.VK_SPACE) {
            evt.consume();

        }
    }//GEN-LAST:event_txtNomProveeKeyTyped

    private void txtTeleProveeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTeleProveeKeyTyped
        char a = evt.getKeyChar();
        if (!Character.isDigit(a)) {
            evt.consume();
        }
        //LIMITE DE CARACTERES//
        if (txtTeleProvee.getText().length() == 9/*LIMITE*/) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTeleProveeKeyTyped

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        Menú menú = new Menú();
        menú.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    public void cargarjtabla() throws SQLException {
        jtablaProveedor.setModel(DbUtils.resultSetToTableModel(objProveedoresL.fillProveedor()));
    }
    private void btnAñadirProveeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirProveeActionPerformed
        if (txtRucProvee.getText().isEmpty()||txtNomProvee.getText().isEmpty()||txtTeleProvee.getText().isEmpty()||txtDireccion.getText().isEmpty()||txtCorreo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,"Campos vacios, verifique su información");
        }
        else{
        modelo.addRow(new Object[]{txtRucProvee.getText(), txtNomProvee.getText(), txtTeleProvee.getText(), txtDireccion.getText(), txtCorreo.getText()});
        jtablaProveedor.setModel(modelo);

        objProveedor.setRuc_Provee(txtRucProvee.getText());
        objProveedor.setTelefono(txtTeleProvee.getText());
        objProveedor.setRazon_Social(txtNomProvee.getText());
        objProveedor.setDireccion(txtDireccion.getText());
        objProveedor.setCorreo(txtCorreo.getText());
        if (objProveedoresL.graba_proveedor(objProveedor)) {
            JOptionPane.showMessageDialog(null, "Se grabó correctamente");
            limpiar();
            try {
                cargarjtabla();
            } catch (SQLException ex) {
                Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se grabó correctamente");
        }
        }
    }//GEN-LAST:event_btnAñadirProveeActionPerformed

    private void btnBuscarProveeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProveeActionPerformed
        objProveedor = objProveedoresL.Busca_Proveedor(JOptionPane.showInputDialog("Inserte su Ruc de Proveedor"));
        if ((objProveedor.getRazon_Social() == "Nada")) {
            JOptionPane.showMessageDialog(null, "Ruc no existe");
            limpiar();
        } else {
            limpiar();
            txtRucProvee.setText(objProveedor.getRuc_Provee());
            txtTeleProvee.setText(objProveedor.getTelefono());
            txtNomProvee.setText(objProveedor.getRazon_Social());
            txtDireccion.setText(objProveedor.getDireccion());
            txtCorreo.setText(objProveedor.getCorreo());
        }
    }//GEN-LAST:event_btnBuscarProveeActionPerformed

    private void btnActuProveeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActuProveeActionPerformed

        objProveedor.setRuc_Provee(txtRucProvee.getText());
        objProveedor.setTelefono(txtTeleProvee.getText());
        objProveedor.setRazon_Social(txtNomProvee.getText());
        objProveedor.setDireccion(txtDireccion.getText());
        objProveedor.setCorreo(txtCorreo.getText());

        if (objProveedoresL.Actualiza_Proveedor(objProveedor)) {
            JOptionPane.showMessageDialog(null, "Se modificó correctamente");
            limpiar();
            try {
                cargarjtabla();
            } catch (SQLException ex) {
                Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se modificó correctamente");
        }
        
    }//GEN-LAST:event_btnActuProveeActionPerformed

    private void btnElimiProveeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimiProveeActionPerformed

        if (objProveedoresL.Eliminar_Proveedor((txtRucProvee.getText()))) {
            JOptionPane.showMessageDialog(null, "Se eliminó con éxito");
            limpiar();
            try {
                cargarjtabla();
            } catch (SQLException ex) {
                Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se eliminó");
        }
    }//GEN-LAST:event_btnElimiProveeActionPerformed

    private void jtablaProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaProveedorMouseClicked

        DefaultTableModel model = (DefaultTableModel) jtablaProveedor.getModel();
        int SelectedRowIndex = jtablaProveedor.getSelectedRow();
        txtRucProvee.setText(model.getValueAt(SelectedRowIndex, 0).toString());
        txtTeleProvee.setText(model.getValueAt(SelectedRowIndex, 1).toString());
        txtNomProvee.setText(model.getValueAt(SelectedRowIndex, 2).toString());
        txtDireccion.setText(model.getValueAt(SelectedRowIndex, 3).toString());
        txtCorreo.setText(model.getValueAt(SelectedRowIndex, 4).toString());
    }//GEN-LAST:event_jtablaProveedorMouseClicked

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        String proveedor = txtBusqueda.getText();
        buscarporRuc(proveedor);
    }//GEN-LAST:event_txtBusquedaKeyReleased
    public void buscarporRuc(String text) {
        DefaultTableModel result = objProveedoresL.BarraBuscarProveedor(text);
        jtablaProveedor.setModel(result);
    }
    
    private void jtablaaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtablaaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Proveedores().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActuProvee;
    private javax.swing.JButton btnAñadirProvee;
    private javax.swing.JButton btnBuscarProvee;
    private javax.swing.JButton btnElimiProvee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTable jtablaProveedor;
    private javax.swing.JScrollPane jtablaa;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNomProvee;
    private javax.swing.JTextField txtRucProvee;
    private javax.swing.JTextField txtTeleProvee;
    // End of variables declaration//GEN-END:variables
}
